import Card from "../components/home/card";
import Layout from "../components/layout";
import Head from "next/head";
import PostDetail from "../components/home/postDetail";
import { useEffect, useState } from "react";
import { Modal } from "flowbite-react";
import dynamic from "next/dynamic";

export default function Home() {
  const [isVisibleForBottomDrawer, setisVisibleForBottomDrawer] =
    useState(false);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className="flex flex-col items-center justify-center min-h-screen">
          <div className="flex flex-col px-5 py-3">
            <Card />
          </div>
          <div className="flex flex-col px-5 py-3">
            <Card />
          </div>
          <div className="flex flex-col px-5 py-3">
            <Card />
          </div>
          <div className="flex flex-col px-5 py-3">
            <Card />
          </div>

          <div className="fixed bottom-0 z-20">
            <div className={isVisibleForBottomDrawer ? "block" : "hidden"}>
              <PostDetail />
            </div>
          </div>
        </div>
      </Layout>
    </div>
  );
}
