import Head from "next/head";
import Layout from "../components/layout";
import PostBox from "../components/posting/postbox";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"
        ></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Layout>
          <div className="flex flex-col items-center justify-center min-h-screen">
            <div className="px-3 py-40">
              <PostBox className="w-full" />
            </div>
          </div>
        </Layout>
      </div>
    </div>
  );
}
